name: bech32
version: 0.1.2
description: Library implementing Bitcoins BIP173 (Bech32 encoding) specification in a Flutter friendly fashion.
author: Harm Aarts <harm@aarts.email>
homepage: https://github.com/haarts/bech32

dependencies:
    convert: ^2.0.2

dev_dependencies:
    test: ^1.3.4
    hex: any
    pedantic: ^1.9.0

environment:
    sdk: ">=2.0.0 <3.0.0"
